### ISSUE TITLE
Cache-busting images?

### ISSUE THREAD

**Issue by krazyjakee** [sathoro/Compressor#8]
With similar methodology, is it possible to test if an image has changed and cache-bust that too with a revision id? I guess that would require something to parse the CSS to find the images, grab the image, test against a hash database and then generate a new cache url.

**Comment by sathoro** [comment]
This plugin was only designed for CSS and JS files. If you are changing images that get referenced in CSS you should probably just manually change the image name. If the images are dynamic and changing a lot I would generate inline CSS and then inside that CSS use some sort of cachebusting method to generate the image URL.
